config/routes.rb
Rails.application.routes.draw do
  resources :projects
  root to: "projects#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many_attached :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :details, :url, :github, image_url: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Igopay</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div> 
  </body>
</html>

app/views/projects/_form.html.erb
<div class="main_form">  
  <%= form_with(model: project, local: true) do |form| %>
    <% if project.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

        <ul>
          <% project.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="field file_upload">
      <%= form.label :image_url %>
      <%= form.file_field :image_url, multiple: true, direct_upload: true, class: "file_upload" %>
    </div>

    
    <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
    </div>
    
    <div class="field">
    <%= form.label :github %>
    <%= form.text_field :github %>
    </div>
    
    <div class="field">
      <%= form.label :details %>
      <%= form.text_area :details, cols: 30, rows: 10 %>
    </div>
    <div class="actions field">
      <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1 class="tac">Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<div class="main_projects container">
  <p id="notice"><%= notice %></p>

  <h1 class="tac">Projects</h1>
<div class="project_cards">
      <% @projects.each do |project| %>
        <div class="project_card">
        <%= project.image_url %>
        <%= project.name %>
          <%= truncate(project.details) %>
          <%= project.url %>
          <%= project.github %>
          <div class="project_card-links">
          <%= link_to 'Show', project %>
          <%= link_to 'Edit', edit_project_path(project) %>
          <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
      <% end %>
</div>

  <br>

  <%= link_to 'New Project', new_project_path %>
</div>

app/views/projects/new.html.erb
<h1 class="tac">New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @project.image_url %>
</p>

<p>
  <strong>Details:</strong>
  <%= @project.details %>
</p>

<p>
  <strong>Url:</strong>
  <%= @project.url %>
</p>

<p>
  <strong>Github:</strong>
  <%= @project.github %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>